# Generated by Django 5.2.4 on 2025-08-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_created_at', models.DateTimeField(auto_now_add=True)),
                ('cart_updated_at', models.DateTimeField(auto_now=True)),
                ('cart_is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
