# Generated by Django 5.2.4 on 2025-08-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('category_description', models.TextField(blank=True)),
                ('category_created_at', models.DateTimeField(auto_now_add=True)),
                ('category_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
