# Generated by Django 5.2.4 on 2025-08-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_item_quantity', models.PositiveIntegerField(default=1)),
                ('product_price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
