# Generated by Django 5.2.4 on 2025-08-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.CharField(max_length=50)),
                ('order_total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_created_at', models.DateTimeField(auto_now_add=True)),
                ('order_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
