# Generated by Django 5.2.4 on 2025-08-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_item_quantity', models.PositiveIntegerField(default=1)),
                ('cart_item_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
