# Generated by Django 5.2.4 on 2025-08-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
    ]
